server:
  port: 8282

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: true
  heathcheck:
    enabled: true

spring:
  application:
    name: nix
  data:
    mongodb.host: localhost
    mongodb.port: 27017
    mongodb.uri: mongodb://localhost/
    mongo.repositories.enabled: true
   